#!/bin/bash
# Migration helper script for converting panic-based error handling to Result types
# This script helps systematically update indicator modules

set -e

echo "=== Centaur Technical Indicators: Error Handling Migration Helper ==="
echo ""
echo "This script helps migrate indicator modules from panic! to Result types"
echo ""

# Function to show module statistics
show_module_stats() {
    local module=$1
    echo "Module: $module"
    echo "  Lines: $(wc -l < src/$module.rs)"
    echo "  Public functions: $(grep -c "pub fn" src/$module.rs || echo "0")"
    echo "  Tests: $(grep -c "#\[test\]" src/$module.rs || echo "0")"
    echo "  Should panic tests: $(grep -c "#\[should_panic" src/$module.rs || echo "0")"
    echo ""
}

# Check if in correct directory
if [ ! -f "Cargo.toml" ]; then
    echo "Error: Must run from repository root"
    exit 1
fi

echo "Current status:"
echo "==============="
show_module_stats "validation"
show_module_stats "moving_average"
show_module_stats "basic_indicators"
show_module_stats "momentum_indicators"

echo ""
echo "Validation module status: ✅ COMPLETE"
echo "Error module status: ✅ COMPLETE"
echo ""

echo "Recommended migration order (smallest to largest):"
echo "1. moving_average.rs (469 lines, 4 functions)"
echo "2. volatility_indicators.rs (416 lines)"
echo "3. chart_trends.rs (635 lines)"
echo "4. correlation_indicators.rs (654 lines)"
echo "5. other_indicators.rs (1,154 lines)"
echo "6. strength_indicators.rs (1,170 lines)"
echo "7. basic_indicators.rs (2,008 lines, 29 functions) - many dependencies"
echo "8. trend_indicators.rs (2,128 lines)"
echo "9. candle_indicators.rs (2,470 lines)"
echo "10. momentum_indicators.rs (4,651 lines, 32 functions)"
echo ""

echo "Common patterns to apply:"
echo "========================"
echo ""
echo "1. Function signatures:"
echo "   Old: pub fn indicator(prices: &[f64]) -> f64"
echo "   New: pub fn indicator(prices: &[f64]) -> crate::Result<f64>"
echo ""
echo "2. Validation calls:"
echo "   Old: assert_non_empty(\"prices\", prices);"
echo "   New: assert_non_empty(\"prices\", prices)?;"
echo ""
echo "3. Function calls that now return Result:"
echo "   Old: let x = some_fn(...);"
echo "   New: let x = some_fn(...)?;"
echo ""
echo "4. Return values:"
echo "   Old: return value;"
echo "   New: return Ok(value);"
echo ""
echo "   Old: value (at end of function)"
echo "   New: Ok(value)"
echo ""
echo "5. Match expressions with unsupported_type:"
echo "   Old: _ => unsupported_type(\"TypeName\"),"
echo "   New: _ => Err(unsupported_type(\"TypeName\")),"
echo ""
echo "6. Documentation:"
echo "   Old: # Panics"
echo "   New: # Errors"
echo ""
echo "7. Tests - successful cases:"
echo "   Old: let result = indicator(...);"
echo "   New: let result = indicator(...).unwrap();"
echo ""
echo "8. Tests - error cases:"
echo "   Old: #[should_panic(expected = \"message\")]"
echo "       fn test_name() { indicator(...); }"
echo "   New: fn test_name() {"
echo "            let result = indicator(...);"
echo "            assert!(result.is_err());"
echo "        }"
echo ""

echo "Testing workflow:"
echo "================"
echo "1. Update module code"
echo "2. Run: cargo check --lib"
echo "3. Fix compilation errors"
echo "4. Update tests"
echo "5. Run: cargo test --lib <module_name>"
echo "6. Verify all tests pass"
echo "7. Run: cargo test --lib (full test suite)"
echo "8. Commit changes"
echo ""

echo "Quick commands:"
echo "==============="
echo "  Check compilation: cargo check --lib"
echo "  Test single module: cargo test --lib basic_indicators"
echo "  Test all: cargo test --lib"
echo "  Show git status: git status"
echo "  Show git diff: git diff src/<module>.rs | less"
echo ""
